openapi: "3.0.0"

info:
  title: My calculator
  version: "0.1.0"
  description: My awesome calc!

paths:
  "/add/{n1}/{n2}":
    get:
      operationId: AddGet
      summary: Adds two numbers
      x-cli-name: add-get
      x-cli-group: ops
      x-cli-aliases:
        - ag

      parameters:
        - name: n1
          required: true
          in: path
          description: The first number
          schema:
            type: integer
        - name: n2
          required: true
          in: path
          description: The second number
          schema:
            type: integer
    post:
      operationId: AddPost
      summary: Adds two numbers via POST
      x-cli-name: add-post
      x-cli-group: ops
      x-cli-aliases:
        - ap

      requestBody:
        description: The numebers map
        required: true
        x-cli-name: nmap
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NumbersMap"
  "/health":
    get:
      operationId: HealthCheck
      summary: Returns Ok if all is well
      x-cli-name: ping
  "/meta":
    get:
      operationId: GetMeta
      summary: Returns meta
      x-cli-ignored: true
  "/info":
    get:
      operationId: GetInfo
      summary: Returns info
      x-cli-group: info

      parameters:
        - name: p1
          required: true
          in: path
          description: The first param
          schema:
            type: integer
        - name: p2
          required: true
          in: query
          description: The second param
          schema:
            type: string
        - name: p3
          required: true
          in: header
          description: The third param
          schema:
            type: number
        - name: p4
          required: true
          in: cookie
          description: The fourth param
          schema:
            type: boolean

components:
  schemas:
    NumbersMap:
      type: object
      required:
        - n1
        - n2
      properties:
        n1:
          type: integer
          description: The first number
        n2:
          type: integer
          description: The second number
